### ISSUE TITLE
My game keeps crashing

### ISSUE THREAD

**Issue by KNIGHTINBLUE** [MightyBunch/MightyRacingMod#1]
whenever i type a command to do with adding myself as a driver my game crashes (it is single player so i can't test it on anyone else. i can see that the command worked though for a brief second before my game closes. i don't know if this is common or how to fix it.

**Comment by MightyBunch** [comment]
Hello! This behavior is unusual. Could you please provide the game logs or crash report so we can look into this further?

**Comment by KNIGHTINBLUE** [comment]
idrk know what it is but i think this is a crash log. its what i said to go to when the game crashed. it feels quite long though. i hope it helps


---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2024-12-28 23:56:28
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'void net.minecraft.class_3222.method_64398(net.minecraft.class_2561)'
	at knot//com.mightyracing.MightyRacingCommand.driver(MightyRacingCommand.java:452)
	at knot//com.mightyracing.MightyRacingCommand.lambda$register$6(MightyRacingCommand.java:94)
	at knot//com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
	at knot//net.minecraft.class_8865.method_54416(class_8865.java:29)
	at knot//net.minecraft.class_8865.execute(class_8865.java:13)
	at knot//net.minecraft.class_8856.method_54405(class_8856.java:8)
	at knot//net.minecraft.class_8847.method_54388(class_8847.java:8)
	at knot//net.minecraft.class_8854.method_54390(class_8854.java:107)
	at knot//net.minecraft.class_2170.method_54313(class_2170.java:379)
	at knot//net.minecraft.class_2170.method_9249(class_2170.java:309)
	at knot//net.minecraft.class_3244.method_58590(class_3244.java:1319)
	at knot//net.minecraft.class_3244.method_44356(class_3244.java:1307)
	at knot//net.minecraft.class_3738.run(class_3738.java:18)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:162)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864)
	at knot//net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:136)
	at knot//net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846)
	at knot//net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840)
	at knot//net.minecraft.class_1255.method_18857(class_1255.java:145)
	at knot//net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:810)
	at knot//net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:815)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.5, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 186155272 bytes (177 MiB) / 1442840576 bytes (1376 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-14400F
	Identifier: Intel64 Family 6 Model 183 Stepping 1
	Microarchitecture: Raptor Lake
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 16
	Graphics card #0 name: Microsoft Basic Display Adapter
	Graphics card #0 vendor: Microsoft
	Graphics card #0 VRAM (MiB): 0.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 10.0.26100.1
	Graphics card #1 name: NVIDIA GeForce RTX 4060 Ti
	Graphics card #1 vendor: NVIDIA
	Graphics card #1 VRAM (MiB): 8188.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 32.0.15.6081
	Graphics card #2 name: Intel(R) UHD Graphics 770
	Graphics card #2 vendor: Intel Corporation
	Graphics card #2 VRAM (MiB): 2048.00
	Graphics card #2 deviceId: VideoController3
	Graphics card #2 versionInfo: 32.0.101.5972
	Graphics card #3 name: NVIDIA GeForce RTX 4060
	Graphics card #3 vendor: NVIDIA
	Graphics card #3 VRAM (MiB): 8188.00
	Graphics card #3 deviceId: VideoController4
	Graphics card #3 versionInfo: 32.0.15.6081
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 4.80
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 4.80
	Memory slot #1 type: Unknown
	Virtual memory max (MiB): 18017.82
	Virtual memory used (MiB): 12681.15
	Swap memory total (MiB): 1792.00
	Swap memory used (MiB): 141.46
	Space in storage for jna.tmpdir (MiB): available: 835897.75, total: 948248.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 835897.75, total: 948248.00
	Space in storage for io.netty.native.workdir (MiB): available: 835897.75, total: 948248.00
	Space in storage for java.io.tmpdir (MiB): available: 835897.75, total: 948248.00
	Space in storage for workdir (MiB): available: 835897.75, total: 948248.00
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M
	Fabric Mods: 
		architectury: Architectury 13.0.8
		boathud_extended: BoatHUD (Extended) 1.1.0
		boathud_f1: BoatHud (F1 2023) 1.1.1
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		fabric-api: Fabric API 0.102.0+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8cd1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.19+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.5.0+c5e2b5c6d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.27+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.16+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae06d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df360d1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209bd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+a551f7a4d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209bd1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49cd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49cd1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b1d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.16+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+176f9036d1
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		java: OpenJDK 64-Bit Server VM 21
		mighty-racing: Mighty Racing Mod fabric1.20.3-1.0.6
		minecraft: Minecraft 1.21
		modmenu: Mod Menu 11.0.3
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		openboatutils: OpenBoatUtils 0.4.3_1.21
		sodium: Sodium 0.6.5+mc1.21.1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19
		squeedometer: Squeedometer 1.1.9
		thirdpersonboating: ThirdPersonBoating 1.0.1
		worldedit: WorldEdit 7.3.8+6939-7d32b45
	Server Running: true
	Player Count: 1 / 8; [class_3222['{MINECRAFT_USERNAME}'/125050, l='ServerLevel[New World]', x=-13.30, y=-60.00, z=160.76]]
	Active Data Packs: vanilla, fabric, fabric-convention-tags-v2
	Available Data Packs: bundle, fabric, fabric-convention-tags-v2, trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -5265578150273052856
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.21

**Comment by MightyBunch** [comment]
Thank you for the logs, they were really helpful! I've found the issue, and it will be fixed in the version I’ll be releasing in the next hour. If you're interested in the technical details: it seems that this issue occurred in versions 1.20.5, 1.20.6, 1.21, and 1.21.1. The problem arose probably because the method "sendMessage" was renamed to "addMessage" in these versions by developers, and then reverted back to "sendMessage" in 1.21.2. As a result, when the mod tried to output text to the chat, the game crashed because it couldn’t find the correct method. Interestingly, the issue didn’t appear during testing in the mod development environment. Quite strange.

**Comment by KNIGHTINBLUE** [comment]
thanks a lot. i appreciate it
